name: invoiceflow
description: Professional invoice management and business analytics app for small businesses and freelancers.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1
  firebase_messaging: ^16.0.1
  
  # Firebase UI
  google_sign_in: ^6.2.1
  path_provider: ^2.1.3
  
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.5
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  sizer: ^2.0.15
  fl_chart: ^0.68.0
  google_fonts: ^6.3.1
  intl: ^0.20.2
  web: any
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  share_plus: ^11.1.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.0
  provider: ^6.1.2
  js: ^0.7.2
  file_picker: ^8.0.5
  csv: ^6.0.0
  flutter_contacts: ^1.1.9
  permission_handler: ^11.3.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^6.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/data/invoices.csv
